#!/bin/bash

HOST="localhost"
USER="qrcofhgs_testuser"
PASSWORD="neodriven"
PORT="3306"
DATABASE="qrcofhgs_testdb"
TABLE="venues"

mysql -uroot <<MYSQL_SCRIPT
DROP DATABASE IF EXISTS $DATABASE;
CREATE DATABASE IF NOT EXISTS $DATABASE;
CREATE USER IF NOT EXISTS '$USER'@'$HOST' IDENTIFIED BY '$PASSWORD';
GRANT ALL PRIVILEGES ON $DATABASE.* TO '$USER'@'$HOST';
FLUSH PRIVILEGES;
USE $DATABASE;
DROP TABLE IF EXISTS $TABLE;
CREATE TABLE IF NOT EXISTS $TABLE (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name TEXT NOT NULL,
 latitude FLOAT NOT NULL,
 longitude FLOAT NOT NULL );
MYSQL_SCRIPT

echo "Done"

